#+INCLUDE: "inc/header.html" export html
#+options: toc:nil
#+OPTIONS: html-postamble:nil
#+OPTIONS: html-style:nil
#+OPTIONS: num:nil p:nil pri:nil stat:nil tags:nil tasks:nil tex:nil timestamp:nil toc:nil title:nil ^:nil
#+INCLUDE: /home/diego/.org-macros/org/org-macros.setup
#+TITLE: SURAGU
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
#+HTML_HEAD_EXTRA: <meta name="description" content="SURAGU.NET --- Existencialismo, tecnología y anime" />
#+HTML_HEAD_EXTRA: <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32x32.png">
#+HTML_HEAD_EXTRA: <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon-16x16.png">
#+EXPORT_FILE_NAME: index.html

* SURAGU
Bienvenido a SURAGU, un sitio web donde hablo de cualquier cosa que se
me ocurra, reseñas, tecnología y contenido de relleno como la
multimedia que he consumido. Por razones históricas parte del
contenido está en inglés.

Todo lo que he creado está bajo la WTFPL o cualquier licencia
equivalente al dominio público

Este sitio literalmente no usa cookies en primer lugar. Así que
incumplimos la GDPR orgullosoamente.

Dejad una firma en el [[https://suragu.net/guestbook/guestbook.cgi][libro de visitas]].

[[https://lain.dance][lain.dance]] inauguración 2024. Sitio web en el que podéis chequear como
se menea.

* Contacto
Para elogios, insultos, trabajos y amenazas de muerte, podeis mandarme
un mail a diego (arroba) suragu [punto] net. Suele funcionar. También
puedes usar XMPP. que es diego (arroba) scaringtheho (punto) es

* Donar

Si quieres ayudarme a defraudar a Hacienda, envía criptomonedas a las
siguientes direcciones:
- Monero: 87nNzDdnACV614EuueWcwiX16hYNr9cVMACzYExHvGRRf2sHDUydjNvFvoMRBRbJntgxanvE9vzGxLTgenydK8PuSMq9aXC
- Bitcoin: bc1q8k6f3ja8na82wl6ehw73uhy67d45pkhs63yvy5    

* Mirrors
Puede ser que ni siquiera funcionen, en tal caso mandarme un correo y
lo arreglaré.
#+begin_export html
<p>
	<a href="http://sukamuzgxigntu7issqf3y5bfsskwg5zzrzbuqjaxxmhkfoxbgiy77qd.onion">[Tor]​</a> <a href="http://46egvt2hpvkqwm5xw4wyyozp6hkwvnmbcys7bi6rh4o4wktllpea.b32.i2p/">[I2P]​</a>
</p>
#+end_export
Sitio generado el {{{time(%Y-%m-%d a las %H:%M)}}}
